### ISSUE TITLE
Strict version contraints causes issues.

### ISSUE THREAD

**Issue by bfanger** [foxdog-studios/three-transformcontrols#2]
**The issue**

The latest version of three is **0.78.0** but this package uses `"dependencies": { "three": "^0.76.1"}` which causes npm to download and use another version which will cause conflics:

`THREE.Object3D.add: object not an instance of THREE.Object3D`

Update this package for every three.js release and/or relax the version contraints (I don't think the TransformControls.js changes/breaks on every release) and/or mark the dependancy as a peerDependancy, like [react-three](https://github.com/Izzimach/react-three/blob/master/package.json#L35)

**A workaround for using the TransformControls in a webpack app:**

``` js
require("three/examples/js/controls/TransformControls");

// in webpack.config.js
plugins: [
    new webpack.ProvidePlugin({
        THREE: "three",
    })
],
```

_(doesn't use the three-transformcontrols package)_

**Comment by eldog** [comment]
Thanks for reporting the issue. I encountered the exact same problem `THREE.Object3D.add: object not an instance of THREE.Object3D` and following your recommendation of relaxing the constraint I changed it to `"dependencies": { "three": ">=0.76.1"}` which resolved it. 

I've also pushed a version for R78, which incorporates the latest changes made in the THREE project.
